### ISSUE TITLE
Dropdown menu for manually added players

### ISSUE THREAD

**Issue by Solaris9** [motzel/ScoreSaberCountryLeaderboard#100]
**Is your feature request related to a problem? Please describe.**
When trying to view another saved user's profile you need to search them by remembering their current username, or copying it from the compare list and then searching, both are not ideal.

**Describe the solution you'd like**
A dropdown for manually added users on the navigation bar. Or possibly a pop out model for both manually added users and country added players.

**Describe alternatives you've considered**
None that provide the same functionality without overriding SSCL (ScoreSaberEnchanced).

**Additional context**
(Dropdown menu when hovered over your profile link on ScoreSaberEnchanced)
![image](https://user-images.githubusercontent.com/33650616/113476965-aeb0d700-9433-11eb-9b27-afd7245cbb97.png)

**Comment by motzel** [comment]
Thank you for the feature request. I already have this on my long term to-do list. It will take some time though, as I have little time to develop the plugin at the moment.

**Comment by Solaris9** [comment]
Closing as it was merged in https://github.com/motzel/ScoreSaberCountryLeaderboard/pull/104
