### ISSUE TITLE
Sort by ACC

### ISSUE THREAD

**Issue by GianniKoch** [motzel/ScoreSaberCountryLeaderboard#102]
Hi, thanks for this great tool btw <3

I was wondering if you think it would be a nice idea to add an additional sort button for ACC, we have top for score, recent for ... recent xd but top acc would be nice too (for example: tournament opponents strong points :p) 

![kinda like this](https://user-images.githubusercontent.com/36133967/115785833-4c0e8380-a3c0-11eb-89b3-d05bd5cfe06a.png)

If you don't like it then that's okay xD I was just thinking about it.

Keep up the good work!

Gianni

**Comment by motzel** [comment]
There is  already such an option. You have to go to cached scores and select ranked maps only (because only for them the accuracy is always available).

![image](https://user-images.githubusercontent.com/1758707/115788168-8e858f80-a3c3-11eb-8085-52f72c101a4e.png)
