### ISSUE TITLE
Adding player to friends list shows up as undefined and unclickable

### ISSUE THREAD

**Issue by burritosoftware** [motzel/ScoreSaberCountryLeaderboard#105]
**Describe the bug**
Adding a player to the friends list makes them show up as undefined. You cannot click on the undefined text either.

**To Reproduce**
1. Add a player to your friends list
2. Refresh, and hover over the friends tab
3. Observe "undefined"

**Expected behavior**
The tab would show the friend's name and allow me to click on it.

**Screenshots**
![image](https://user-images.githubusercontent.com/37681398/121627399-1daa3d80-ca2c-11eb-8310-91d3384c63f5.png)

**Please complete the following information:**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Browser version: 91.0.864.41
 - Userscript loader: Violentmonkey

**Comment by motzel** [comment]
Hi,

Thanks for a bug report! However, I am unable to reproduce it in any way.
The only possibility I can see is right after the addition, when the player data could not be retrieved from the ScoreSaber API. 
Do you still have this problem?

**Comment by burritosoftware** [comment]
Yep

**Comment by motzel** [comment]
Since I am unable to reproduce this bug I will need to export your plugin data. Please catch me on discord at motzel#8017.

**Comment by motzel** [comment]
Closed due to lack of additional information
