### ISSUE TITLE
Adding profiles outside top 50 to country standings

### ISSUE THREAD

**Issue by Omurky** [motzel/ScoreSaberCountryLeaderboard#106]
Hi motzel,

It would be nice for users to be able to manually add users outside of the top 50 to count towards country standing stats. This becomes mostly relevant for acc / low star maps, where the top plays are not always set by the players with the highest pp standing in a given country.

Alternatively, since the score caching is already done for added "friend profiles", you could automatically include those scores in country standing stats if the added friend profile is from the same country.

Thanks for the fantastic userscript!

Omurky

**Comment by motzel** [comment]
Hi, thx for a feature request. This was something I was supposed to add myself a while back but forgot ;-)

Pls update to v1.7.2

![image](https://user-images.githubusercontent.com/1758707/121801705-f8d6e580-cc38-11eb-88f1-39c8190db24a.png)
