### ISSUE TITLE
PP Graph stopped updating

### ISSUE THREAD

**Issue by Velheor9001** [motzel/ScoreSaberCountryLeaderboard#78]
![image](https://user-images.githubusercontent.com/46257780/100780300-62d71e00-33be-11eb-961d-acdc665ca8cf.png)

**Comment by motzel** [comment]
That's strange. Can you write which version of the plugin you use? Have you updated to the latest one? And what browser (and version) do you use?

**Comment by Velheor9001** [comment]
v0.9.9.2, Chrome 87.0.4280.66 
Refreshing global cache/reinstalling the script doesn't help.

**Comment by motzel** [comment]
Something must have gone wrong with converting the database after the update.
Do you use Discord? Could you contact me at motzel#8017 ? I will give you information how to restore an older version of the plugin and ask you to export the data for analysis.

**Comment by motzel** [comment]
Fixed in 0.9.9.3, please update
