### ISSUE TITLE
Same score order is alphabetical.

### ISSUE THREAD

**Issue by MakeMonni** [motzel/ScoreSaberCountryLeaderboard#99]
The same score on the same map by different players is ordered alphabetically instead of submit date as it should be.

This can be seen on this maps leaderboard on the finnish ladder https://scoresaber.com/leaderboard/219995?page=1

A picture for reference.
![kuva](https://user-images.githubusercontent.com/46992293/111376847-a5401480-86a8-11eb-9070-1f064e6f115e.png)

**Comment by motzel** [comment]
You're right. I don't sort by any field other than the score at all. I will correct this as next after releasing the new version I am currently working on.
